###
GET http://localhost:80/api/view?key=tWyV2KiZ1YFfqEUiBYg4g8sK3ot72nihkK9AMMZb
Accept: application/json

###
GET http://localhost:80/api/key?key=tWyV2KiZ1YFfqEUiBYg4g8sK3ot72nihkK9AMMZb
Accept: application/json

###
GET http://localhost:8080/api?key=123456789
Accept: application/json

###
POST http://localhost:8080/api
Content-Type: application/json

{
  "prayer": "Ich bin krank",
  "is_public": true
}


###
PUT http://localhost:80/api?key=tWyV2KiZ1YFfqEUiBYg4g8sK3ot72nihkK9AMMZb
Content-Type: application/json

{
  "id": 1,
  "is_public": false,
  "approved": true
}


###
POST http://localhost:80/api/key?key=tWyV2KiZ1YFfqEUiBYg4g8sK3ot72nihkK9AMMZb
Content-Type: application/json

{
  "key": "1234567899876543219874563214578965412",
  "type": 2
}

###
PUT http://localhost:80/api/key?key=tWyV2KiZ1YFfqEUiBYg4g8sK3ot72nihkK9AMMZb
Content-Type: application/json

{
  "key": "1234567899876543219874563214578965412"
}
