version: '3.3'
services:

services:

  traefik:
    image: "traefik:v2.2"
    container_name: "traefik"
    command:
      - "--log.level=DEBUG"
      #- "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--certificatesresolvers.myresolver.acme.httpchallenge=true"
      - "--certificatesresolvers.myresolver.acme.httpchallenge.entrypoint=web"
      - "--certificatesresolvers.myresolver.acme.caserver=https://acme-staging-v02.api.letsencrypt.org/directory"
      - "--certificatesresolvers.myresolver.acme.email=server@revwal.de"
      - "--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json"
    ports:
      - "80:80"
      - "443:443"
      #- "8080:8080"
    volumes:
      - "/var/data/letsencrypt:/letsencrypt"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"

  5pm:
    image: 5pm:0.3
    container_name: 5pm
    name: 5pm
    #build: .
    ports:
      - "8080:8080"
    environment:
      - PORT=8080
      - DB_PATH=/data/pray.db
      - MASTERKEY
    restart: always
    volumes:
      - /var/5pm:/data:consistent
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.5pm.rule=Host(`gebet.revwal.de`)"
      - "traefik.http.routers.5pm.entrypoints=websecure"
      - "traefik.http.routers.5pm.tls.certresolver=myresolver"
